[package]
name = "cgroup-sock-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = "0.10.7"
aya-log = { git = "https://github.com/aya-rs/aya-log", tag = "aya-log-v0.1.9" }
#aya-log = "0.1.9"
cgroup-sock-test-common = { path = "../cgroup-sock-test-common", features=["user"] }
anyhow = "1.0.42"
clap = { version = "3.1", features = ["derive"] }
log = "0.4"
simplelog = "0.12"
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }

[[bin]]
name = "cgroup-sock-test"
path = "src/main.rs"
